name: playground pipeline

on:
  push:
    branches:
      - 'master'
    workflow_dispatch:
    workflow_call:

env:
  PROJECT_ID: schulung-b14-c146
  PROJECT_LOCATION: europe-west3
  DOCKER_REPO: europe-west3-docker.pkg.dev/schulung-b14-c146/playground-docker

jobs:
  build-image:
    runs-on: macOS-12
    environment: DEV
    permissions:
      contents: 'read'
      actions: 'write'
      id-token: 'write'
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3
      - name: Authentication
        id: auth
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.PROJECT_SA_KEY }}
          export_environment_variables: true
          retries: 5
          backoff: tr
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1.1.0

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build Docker Images PLAYGROUND
        working-directory: .
        run: |
          docker build -t playground .

      - name: Tag and Push Docker Images PLAYGROUND
        run: |
          docker tag playground ${DOCKER_REPO}/playground:${GITHUB_SHA}
          docker push ${DOCKER_REPO}/playground:${GITHUB_SHA}
